// Is the software actually winning?
//
// The performance page reports a win rate. That is not the same question. A
// win rate says what happened; it does not say whether the system is doing
// what it exists to do, whether that is getting better or worse, or whether
// the number can be trusted yet.
//
// Two measurement traps make the naive version worse than useless, and both
// showed up the first time this was computed:
//
//   SURVIVORSHIP. Losers resolve faster than winners — a stop is hit in hours,
//   a target takes a day or more. So any recent window counts the quick losses
//   and misses the slow wins still running. Measured that way the last seven
//   days read -0.311R while the mature record read -0.171R. Only cohorts old
//   enough to have resolved are counted here.
//
//   STALE CALIBRATION. Settings changed on 24 Aug 2026. Judging the current
//   configuration on trades generated by the previous one reports the old
//   system's failure forever and never notices the new one working. Trades are
//   grouped by the calibration in force when they were signalled.
//
// The goals themselves are deliberately few. Expectancy is the one that
// decides whether the system makes money; the rest are diagnostic.
import { getAllSignals } from './signalLog.js';
import { getLearningState } from './learning.js';
import { realisedR, expectancyOf } from './realisedR.js';

// When the calibration materially changed. Trades before this were produced by
// different settings and cannot judge the current ones.
const CALIBRATION_EPOCH = Date.UTC(2026, 7, 24);

// A trade is only safe to count once enough time has passed that it MUST have
// resolved one way or the other — otherwise the quick losses are counted and
// the slow wins are still running, and the record reads worse than it is.
// That moment is the market's own horizon, past which the monitor expires the
// signal regardless. Holding crypto to the 5-day stock horizon just delayed
// honest feedback by three days for no gain.
const MATURE_HOURS = { crypto: 48, stocks: 120, forex: 120, commodities: 120 };
const DEFAULT_MATURE_HOURS = 120;
const MIN_JUDGE    = 40;    // resolved trades before a verdict is offered

const GOALS = {
  expectancy: { target: 0,    label: 'Makes money',        unit: 'R per trade',
                describe: v => `${v >= 0 ? '+' : ''}${v.toFixed(3)}R per trade` },
  greenRate:  { target: 0.70, label: 'Trades finish green', unit: '%',
                describe: v => `${(v * 100).toFixed(0)}% end in profit or breakeven` },
  winRate:    { target: null, label: 'Beats its own breakeven', unit: '%',
                describe: v => `${(v * 100).toFixed(0)}% reach target` }
};

/** Realised R for one closed signal, under the scale-out plan. */

function measure(rows) {
  const vals = rows.map(realisedR).filter(v => v !== null);
  if (!vals.length) return null;
  const wl = rows.filter(s => s.outcome === 'WIN' || s.outcome === 'LOSS');
  const wins = wl.filter(s => s.outcome === 'WIN').length;
  const green = vals.filter(v => v >= 0).length;
  const rr = rows.map(s => s.rrRatio).filter(Boolean);
  const avgRR = rr.length ? rr.reduce((a, b) => a + b, 0) / rr.length : 0;
  return {
    n: vals.length,
    expectancy: vals.reduce((a, b) => a + b, 0) / vals.length,
    greenRate: green / vals.length,
    winRate: wl.length ? wins / wl.length : null,
    avgRR,
    breakeven: avgRR ? 1 / (1 + avgRR) : null
  };
}

/**
 * Where the system stands against what it is for.
 * Reports honestly when there is not enough evidence yet, rather than
 * offering a verdict on a handful of trades.
 */
export function assessGoals() {
  const all = getAllSignals();
  const now = Date.now();
  // The hand-set recalibration, or the last change learning made on its own,
  // whichever is more recent.
  let epoch = CALIBRATION_EPOCH;
  try {
    const learnedAt = Date.parse(getLearningState()?.lastChangeAt || '');
    if (Number.isFinite(learnedAt) && learnedAt > epoch) epoch = learnedAt;
  } catch { /* fall back to the hand-set date */ }
  const mature = s => s.status === 'CLOSED'
    && (now - s.signaledAt) > (MATURE_HOURS[s.market] ?? DEFAULT_MATURE_HOURS) * 3600000;

  const current  = all.filter(s => s.signaledAt >= epoch && mature(s));
  const previous = all.filter(s => s.signaledAt <  epoch && mature(s));
  const pendingCurrent = all.filter(s => s.signaledAt >= epoch && s.status === 'OPEN').length;

  const cur = measure(current);
  const prev = measure(previous);

  // ── THE WHOLE-RECORD VERDICT ────────────────────────────────────────
  //
  // Separate from the calibration comparison above, which only ever looks at
  // trades since the last settings change and so stays silent for weeks. This
  // asks the blunt question over every trade that was actually entered: does
  // this make money? A confidence interval sitting entirely below zero is not
  // a bad patch, it is a measured negative edge, and the honest response is to
  // say so on the page rather than keep presenting cards that look tradeable.
  //
  // Signals whose entry never filled are excluded by realisedR — there was no
  // position — and the fill rate is reported alongside so the two are never
  // confused.
  const entered = all.filter(s => s.status === 'CLOSED' && s.closeReason !== 'NEVER_FILLED');
  const neverFilled = all.filter(s => s.closeReason === 'NEVER_FILLED').length;
  const whole = expectancyOf(entered);
  const edge = whole.n >= 100 && whole.upper !== null ? {
    n: whole.n,
    neverFilled,
    expectancy: parseFloat(whole.mean.toFixed(3)),
    low: parseFloat(whole.lower.toFixed(3)),
    high: parseFloat(whole.upper.toFixed(3)),
    totalR: parseFloat((whole.mean * whole.n).toFixed(1)),
    verdict: whole.upper < 0 ? 'NEGATIVE'
           : whole.lower > 0 ? 'POSITIVE'
           : 'UNPROVEN',
    headline: whole.upper < 0
      ? `Measured edge is negative: ${whole.mean.toFixed(3)}R per trade over ${whole.n} entered trades, and the whole confidence interval sits below zero. Trading this loses money.`
      : whole.lower > 0
        ? `Measured edge is positive: +${whole.mean.toFixed(3)}R per trade over ${whole.n} entered trades.`
        : `No measurable edge either way: ${whole.mean.toFixed(3)}R over ${whole.n} trades, interval spans zero. Not proven to make or lose money.`
  } : null;

  const goals = [];
  const enough = cur && cur.n >= MIN_JUDGE;

  if (!enough) {
    goals.push({
      key: 'evidence', label: 'Enough evidence to judge', status: 'waiting',
      detail: `${cur ? cur.n : 0} of ${MIN_JUDGE} resolved trades under the current settings`
            + (pendingCurrent ? `, ${pendingCurrent} still running` : ''),
      note: 'Settings changed on 24 Aug. Earlier trades were produced by different ones and cannot judge these.'
    });
  } else {
    const g = GOALS.expectancy;
    goals.push({
      key: 'expectancy', label: g.label,
      status: cur.expectancy > 0.05 ? 'ok' : cur.expectancy > -0.05 ? 'marginal' : 'off',
      detail: g.describe(cur.expectancy) + ` over ${cur.n} trades`,
      value: +cur.expectancy.toFixed(3)
    });
    goals.push({
      key: 'greenRate', label: GOALS.greenRate.label,
      status: cur.greenRate >= 0.70 ? 'ok' : cur.greenRate >= 0.55 ? 'marginal' : 'off',
      detail: GOALS.greenRate.describe(cur.greenRate) + ` (aiming for 70%)`,
      value: +(cur.greenRate * 100).toFixed(0)
    });
    if (cur.winRate != null && cur.breakeven != null) {
      const margin = cur.winRate - cur.breakeven;
      goals.push({
        key: 'winRate', label: GOALS.winRate.label,
        status: margin > 0.05 ? 'ok' : margin > -0.02 ? 'marginal' : 'off',
        detail: `${(cur.winRate*100).toFixed(0)}% reach target, needs ${(cur.breakeven*100).toFixed(0)}% at ${cur.avgRR.toFixed(2)}:1`,
        value: +(margin * 100).toFixed(0)
      });
    }
  }

  // Direction of travel, only where both sides have enough to compare.
  let trend = null;
  if (cur && prev && cur.n >= 20 && prev.n >= 20) {
    const delta = cur.expectancy - prev.expectancy;
    trend = {
      delta: +delta.toFixed(3),
      direction: delta > 0.05 ? 'improving' : delta < -0.05 ? 'degrading' : 'flat',
      detail: `${cur.expectancy >= 0 ? '+' : ''}${cur.expectancy.toFixed(3)}R now against `
            + `${prev.expectancy >= 0 ? '+' : ''}${prev.expectancy.toFixed(3)}R under the previous settings`,
      currentN: cur.n, previousN: prev.n
    };
  }

  const offTrack = goals.filter(g => g.status === 'off').length;
  return {
    status: !enough ? 'waiting' : offTrack ? 'off' : goals.some(g => g.status === 'marginal') ? 'marginal' : 'ok',
    headline: !enough
      ? `Gathering evidence — ${cur ? cur.n : 0}/${MIN_JUDGE} trades under current settings`
      : offTrack
        ? `${offTrack} goal${offTrack === 1 ? '' : 's'} not being met`
        : 'Meeting its goals',
    goals, trend,
    current: cur, previous: prev, pendingCurrent,
    edge,
    calibrationEpoch: new Date(epoch).toISOString().slice(0, 10),
    assessedAt: new Date().toISOString()
  };
}
